names:
  0: metro
  1: destornillador
  2: martillo
  3: pinzas
  4: alicate
  5: llave_inglesa
  6: llave_combinada
  7: brocha
  8: espatula
  9: llave_tubo
nc: 10
path: C:\Users\Juan M\Documents\U\Semestre 2026-1\Vision Artificial\toolkit-img-recognition\data\augmented
test: images/test
train: images/train
val: images/val
